### ISSUE TITLE
Samenwerking lectoraat?

### ISSUE THREAD

**Issue by CharleyMuhren** [fdnd/task#1]
N.a.v. vraag van Jurrien in TNO aanvraag: Ik heb het vorig jaar bij Sabine (Visual Methodologies) gepolst. Zij vond het prima maar er is nog niets concreets uitgekomen. Ik denk ook dat een lectoraat als Crossmedia of Digital Life beter aansluit.

**Comment by joostf** [comment]
Samenwerking met lectoraat HBO-ICT noemen
