### ISSUE TITLE
Training: examencommissie

### ISSUE THREAD

**Issue by CharleyMuhren** [fdnd/task#10]

**Comment by ju5tu5** [comment]
Afspraak met Antoinette van Berkel voor dinsdag 19 januari. Zij is verantwoordelijk voor de assessorentraining van de HvA Academie.

**Comment by ju5tu5** [comment]
Gesprek met Katinka, Charley en Michel om de toetsing bij FDND door te nemen. Ter voorbereiding Bijlage 6: Didactiek en Toetsing doorlezen.
